# Generated by Django 3.1.5 on 2021-10-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='isAccepted',
            new_name='is_accepted',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='itemName',
            new_name='item_name',
        ),
    ]
